/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallasavance;

import javax.swing.JFrame;
import dao.Producto;
import dao.Store;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pantallasavance.ClienteFrm;
import dao.Cliente;
import dao.Documento;
import dao.LobbyStats;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Admin
 */
public class Documentos extends javax.swing.JDialog {

    /**
     * Creates new form Clientes
     */
    public Documento documento;
    public Vector<Documento> documentos;

    public Documentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        Store.centerFrame(this);
        this.documento = null;
        this.documentos = new Vector<Documento>();
        Documentos $vm = this;
        this.table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent mouseEvent) {
                $vm.mapFields();
            }
        });
        Store.attachKeys(this, false);
        this.mapFields();
        this.table.requestFocus();
        
        ActionListener cancelarDocListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                $vm.btnCancelarActionPerformed(e);
            }
        };

        $vm.getRootPane().registerKeyboardAction(cancelarDocListener,
                KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);

    }

    public void mapFields() {
        int row = table.getSelectedRow();
        
        if (row != -1) {
            this.documento = documentos.get(row);
        }
        
        documentos = Documento.find();
        String[] header = {"Id", "Documento", "Estado", "Tipo", "Cliente", "Total"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;//This causes all cells to be not editable
            }
        };
        dtm.setColumnIdentifiers(header);
        this.table.setModel(dtm);
        int idx = -1;
        for (Documento d : documentos) {
            String datos[] = new String[header.length];
            String $tipo = d.tipo_documento.tipo == 0 ? "Salida" : "Entrada";
            String $estado = d.id_status == 0 ? "Cancelado" : "Vigente";
            datos[0] = String.valueOf(d.id);
            datos[1] = String.format("%s-%d", d.tipo_documento.serie, d.folio);
            datos[2] = $estado;
            datos[3] = $tipo;
            datos[4] = d.cliente.nombre;
            datos[5] = String.format("$%.2f", d.total);
            dtm.addRow(datos);
            if (this.documento != null && d.id == this.documento.id) {
                idx = dtm.getRowCount() - 1;
            }
        }
        if (idx != -1) {
            this.table.setRowSelectionInterval(idx, idx);
        }
        this.labelTooltip.setText(String.format("Mostrando %d de %d registros", dtm.getRowCount(), dtm.getRowCount()));

        // actualizar stats
        LobbyStats stats = LobbyStats.get();
        this.labelVentas.setText(
                String.format("Ventas: $%.2f MXN", stats.total_ventas, stats.ventas)
        );
        this.labelCompras.setText(
                String.format("Compras: $%.2f MXN", stats.total_compras, stats.compras)
        );
        this.labelUtilidades.setText(String.format("Utilidades: $%.2f MXN", stats.total_utilidades));
        // toggle cancelar btn
        this.btnCancelar.setEnabled(this.documento != null && this.documento.id_status == 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        labelTooltip = new javax.swing.JLabel();
        labelVentas = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        labelCompras = new javax.swing.JLabel();
        labelUtilidades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Documentos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 109, 186));
        jPanel1.setForeground(new java.awt.Color(0, 109, 186));

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(labelTitle.getFont().deriveFont(labelTitle.getFont().getSize()+6f));
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Documentos");

        jScrollPane1.setForeground(new java.awt.Color(200, 200, 200));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        labelTooltip.setText("--- tooltip ---");

        labelVentas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelVentas.setText("Ventas: ---");

        btnCancelar.setBackground(new java.awt.Color(186, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar documento seleccionado (F1)");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        labelCompras.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelCompras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCompras.setText("Compras: ---");

        labelUtilidades.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelUtilidades.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUtilidades.setText("Utilidades: ---");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCompras)
                            .addComponent(labelVentas)
                            .addComponent(labelUtilidades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTooltip)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTooltip)
                    .addComponent(labelVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUtilidades)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.mapFields();
        if (this.documento == null)
            return;
        String msg = String.format(
                "Estas apunto de cancelar el documento %s-%d.\n"
                + "Este cambio será irreversible. La existencia\n"
                + "de los productos será devuelta.", this.documento.tipo_documento.serie,
                this.documento.folio);
        boolean ok = Store.question("¿Estas seguro?", msg);
        if (!ok){
            return;
        }
        
        boolean result = this.documento.cancelar();
        if (!result)
            Store.error("Ha ocurrido un problema", "No se ha podido cancelar el documento por razones desconocidas.");
        this.mapFields();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKeyPressed

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        // TODO add your handling code here:
        this.mapFields();
    }//GEN-LAST:event_tableKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Documentos dialog = new Documentos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCompras;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTooltip;
    private javax.swing.JLabel labelUtilidades;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
